services:
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger-ui
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=/openapi.yml
    volumes:
      - ./openapi.yml:/openapi.yml:ro
    restart: unless-stopped
